spring.application.name=registration-spring-boot
server.port=${HTTP_PORT}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.thymeleaf.cache=false

server.error.include-message=always
